# Generated by Django 4.0.3 on 2023-04-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'List of Members'},
        ),
    ]
