# Generated by Django 4.0.3 on 2023-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
